language: php

php:
  - 5.3
  - 5.4
before_script:
  - ./.travis/install.sh

script: phpunit --coverage-text --configuration ./tests/phpunit.xml

notifications:
    email:
        - padraic.brady@gmail.com