language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 5.3.3 #This will actually use PHP7
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./travis/before_install.sh

install:
  - travis_retry ./travis/install.sh

before_script:
  - ./travis/before_script.sh

script:
  - ./travis/script.sh

after_script:
  - ./travis/after_script.sh
notifications:
  email:
    - padraic.brady@gmail.com
    - dave@atstsolutions.co.uk
  irc: "irc.freenode.org#mockery"
