language: php
php:
  - 5.3
  - 5.4
before_script:
  - "apt-get install php-pear"
  - "pear channel-discover hamcrest.googlecode.com/svn/pear"
  - "pear install -f hamcrest/Hamcrest"
  - "phpenv rehash"
script: phpunit --coverage-text --configuration ./tests/phpunit.xml
notifications:
    email:
        - padraic.brady@gmail.com