language: php
php:
  - 5.3
  - 5.4
before-script:
  - "pyrus channel-discover hamcrest.googlecode.com/svn/pear"
  - "pyrus install -f hamcrest.googlecode.com/svn/pear/Hamcrest"
  - "phpenv rehash"
script: phpunit --coverage-text --configuration ./tests/phpunit.xml
notifications:
    email:
        - padraic.brady@gmail.com